#!/bin/sh

command=$1
expdir=$2
recipe=$3
arguments="${@:4}"
basedir=$(dirname "$0")
pwd=$(pwd)

allowed="dataprep cross_validation train test sweep"

if [ $# -lt 3 ]; then
  echo "ERROR: incorrect command usage"
  echo "run command expdir recipe [optional arguments]"
  if [[ $allowed =~ (^|[[:space:]])"$command"($|[[:space:]]) ]] \
      && [ ! -z $command ]; then
    echo "$command usage:"
    python assist/scripts/prepare_$command.py --help
  fi
  exit 1
fi

if ! [[ $allowed =~ (^|[[:space:]])"$command"($|[[:space:]]) ]]; then
  echo "ERROR: unknown command $command must be one of $allowed"
  exit 1
fi

if [ ! -d "$recipe" ]; then
  echo "canot find recipe $recipe"
  exit 1
fi

python assist/scripts/prepare_$command.py $expdir $recipe $arguments
